prompts = [
    'A glowing neon cityscape at dusk, digital art',
    'A mystical forest with floating lanterns, digital painting',
    'An underwater world with vibrant coral reefs and colorful fish, digital illustration',
    'A steampunk-inspired airship soaring through the clouds, 3D art',
    'A futuristic robot playing a musical instrument, digital art',
    'A magical castle floating in the sky, digital painting',
    'A serene waterfall surrounded by lush greenery, traditional watercolor',
    'A surreal landscape with floating islands and flying whales, digital art',
    'A cozy cafe in a quaint European town, lomography',
    'A space explorer discovering a new planet, digital illustration',
    'A whimsical garden with talking flowers, digital painting',
    'A retro arcade filled with nostalgic games, pixel art',
    'A tranquil lake reflecting the starry night sky, oil painting',
    'A bustling street market with vibrant colors and exotic fruits, digital art',
    'A dreamy seascape with a mermaid sitting on a rock, digital painting',
    'A cosmic journey through a wormhole, digital illustration',
    'A charming cottage in a field of blooming sunflowers, acrylic painting',
    'A futuristic city with flying cars and holographic billboards, digital art',
    'A majestic mountain range at sunrise, digital painting',
    'A fairytale castle surrounded by a moat, watercolor',
    'A magical bookshelf filled with floating books, digital illustration',
    'An enchanted forest with glowing fireflies, digital art',
    'A serene Japanese garden with cherry blossoms, traditional ink painting',
    'A futuristic space station orbiting a distant planet, 3D art',
    'A hidden waterfall in a tropical rainforest, digital painting',
    'A bustling harbor with sailboats and seagulls, oil painting',
    'A cozy cabin covered in snow in the middle of a winter forest, digital art',
    'A mystical cave filled with crystals and glowing mushrooms, digital illustration',
    'A vibrant street art scene with colorful murals, spray paint art',
    'A tranquil countryside scene with rolling hills and grazing sheep, pastel drawing',
    'A futuristic cyberpunk cityscape with flying cars, digital art',
    'A whimsical carousel in an enchanted forest, watercolor painting',
    'A serene beach sunset with palm trees, digital painting',
    'A surreal abstract art piece with vibrant colors and geometric shapes, mixed media',
    'A magical unicorn galloping through a meadow, digital illustration',
    'An ancient ruins temple in the jungle, oil painting',
    'A futuristic sci-fi spaceship docking at a space station, 3D art',
    'A peaceful countryside landscape with a winding river, acrylic painting',
    'A portrait of a loved one in a pop art style, digital illustration',
    'A dynamic street scene with bustling city life, impressionist painting',
    'A mystical wizard conjuring spells in a moonlit forest, digital art',
    'A vibrant floral still life arrangement, watercolor painting',
    'A futuristic robot exploring a post-apocalyptic city, digital art',
    'A dreamy ethereal portrait with glowing elements, digital painting',
    'A whimsical hot air balloon festival in the sky, mixed media',
    'A tranquil zen garden with raked sand and bonsai trees, ink painting',
    'An abstract expressionist artwork with bold brushstrokes and intense colors, oil painting',
    'A futuristic city skyline with flying saucers, digital art',
    'A peaceful countryside cottage with blooming flower gardens, pastel drawing',
    'A surrealistic portrait with melting elements, digital illustration'
]
